services:
  db:
    build: ./mysql_image
    container_name: mysql_db
    restart: always
    command: --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projet_solarx
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
      UPLOAD_LIMIT: 100M
    ports:
      - "80:80"

  python_app:
    build: ./python_image
    container_name: python_env
    restart: always
    depends_on:
      db:
        condition: service_healthy
      nodejs:
        condition: service_started
    environment:
      DB_HOST: "${DB_HOST:-db}"
      NODE_HOST: "${NODE_HOST:-localhost}"
      NODE_PORT: "${NODE_PORT:-3000}"
    volumes:
      - ../dashboard_docker:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "8050:8050"

  nodejs:
    build: ./node_image
    container_name: nodejs
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  db_data:
