services:
  python_app:
    build: ./python_image
    container_name: python_env
    restart: always
    environment:
      DB_HOST: "${DB_HOST:-db}"
      NODE_HOST: "${NODE_HOST:-localhost}"
      NODE_PORT: "${NODE_PORT:-3000}"
    volumes:
      - ../dashboard_docker:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "8050:8050"

volumes:
  db_data:
