global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitoring de Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitoring des métriques système (CPU, RAM, Disk)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Monitoring MySQL
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

  # Monitoring de l'app Python (après instrumentation)
  - job_name: 'python-app'
    static_configs:
      - targets: ['python_app:8050']
    metrics_path: '/metrics'

  # Monitoring Docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
